[[tree_sitter_ocaml]]
arch = "aarch64"
git-tree-sha1 = "9e940cbda17967d8c673c61907cb8ac0a12fdce5"
os = "macos"

    [[tree_sitter_ocaml.download]]
    sha256 = "ebcea3756a99909d35802f7533bfbb454af531615a92c471de1f5c49b9ef880b"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.aarch64-apple-darwin.tar.gz"
[[tree_sitter_ocaml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06acb7d2e967d95f613e26208d2e35aa45abfc78"
libc = "glibc"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "b2a7c6d15fac149e6c24ac76fc730562ce3e81bd406ed70af23ec420059b9853"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.aarch64-linux-gnu-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "757d3cdc0c15815e9e4c4d79923bc4d8fd0b482f"
libc = "musl"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "5f41d523818473159c41626a6f76d1c207cba482d8cd16e248670378dc1d6beb"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.aarch64-linux-musl-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "aarch64"
git-tree-sha1 = "044778369591a0c049dad2bea061bc84641107d9"
os = "freebsd"

    [[tree_sitter_ocaml.download]]
    sha256 = "fd76fa9ae500adff2058f937ae584b4a82787c3ee1ef6b8ff878b318bc90ee78"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.aarch64-unknown-freebsd.tar.gz"
[[tree_sitter_ocaml]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9cbf1020f238df799a4d94f7c85b1fc786d0a93a"
libc = "glibc"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "fceae5ee0ea9a61490977482c5338534a35dbf5ca7528e3eae26a9a76d273c1a"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f686f8c221bcdb9687848f2cc1beb41fad72a1ca"
libc = "musl"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "12c69cafe7355cd045a4f00f3b18ef8d89f4f2fbd06c9f99c745871d6650e611"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e03ced90f6cd43358f04723be657b53fc46c4b4"
libc = "glibc"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "8551c719e163d71d964ba1f00c803219a4a3bd2bfdd61aae86cbc09e05d9a687"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9de60436f8199b74af91444313f3ddce2f6abe22"
libc = "musl"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "96c39ca80e5acfa5ff1350b79960918242aafde2d380d5c7b844069e67390f31"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "269e526a958ba0f6c4b91afd68dd26e8d5953a1a"
libc = "glibc"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "ed5f4723e77c509ff679f3475ca95de455c3cb06d333f5b2af654a669e49e753"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.i686-linux-gnu-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "626843122e0d55327524602c99a0ab4cfbf94b49"
libc = "musl"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "e0cd8a25128b195445569824e0b8fd3c4f5397e903656e9f96e81b58cfb48976"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.i686-linux-musl-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9a1f615d8563a5f53bef3efbfe0db84ba3ecda9"
os = "windows"

    [[tree_sitter_ocaml.download]]
    sha256 = "89ab2665a99d549712557b8eced8237aa90f3d710f15921deccb8b972144fcd2"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.i686-w64-mingw32-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "264b41637b3339e3d8a048ecef13dada64db0a7d"
libc = "glibc"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "4fe4aab81913d76e93b5dff6a5fa838958527a203c7c283001fe799811fd4022"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29ecfc062712229bc8972119fbf47f181df23821"
libc = "glibc"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "17918c026c0513ad082aa413e154af7f30df4b3e39b2d4d04123536ab9cbee6b"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.riscv64-linux-gnu-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "x86_64"
git-tree-sha1 = "d3c390eaae24439db985875ecab047cac76d2e3a"
os = "macos"

    [[tree_sitter_ocaml.download]]
    sha256 = "40d5860ce44c75cd729828dd2af4d0fe3dc0073a1376cae52c5d9a849c36ca2b"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.x86_64-apple-darwin.tar.gz"
[[tree_sitter_ocaml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "908fa7d9ac03ef18f779797495a87f7b03438e3b"
libc = "glibc"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "ebf102b4815e687df3908a760b9a6b322ac693ccb0c481af05850be7ff34fd45"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.x86_64-linux-gnu-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d86d9b878b3ba095e725e55877a7467fedf8563b"
libc = "musl"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "f7715a7f683e6040807c5cfb03b8f9b2f814ec0b566177e47f4f24ddadbec223"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.x86_64-linux-musl-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "x86_64"
git-tree-sha1 = "c5b89187ceea57241a4f4f2f8e6d8bec69b904af"
os = "freebsd"

    [[tree_sitter_ocaml.download]]
    sha256 = "d3ab5f92961e4394466e4024e5299f1d380d0195d3d88b9de62dac9d8fff6bb1"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.x86_64-unknown-freebsd.tar.gz"
[[tree_sitter_ocaml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6df4880e9e53503096e1d9ed67926b9e9838f86d"
os = "windows"

    [[tree_sitter_ocaml.download]]
    sha256 = "a19e6ba96c5a9d36fa26d3f2081a6a20f7d4cae8ee36c7d0e0c98d9ece6c7cdf"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.24.2+0/tree_sitter_ocaml.v0.24.2.x86_64-w64-mingw32-cxx11.tar.gz"
