[[tree_sitter_ocaml]]
arch = "aarch64"
git-tree-sha1 = "c63566f39e0bfd8611931b222af7caa4f4e189a5"
os = "macos"

    [[tree_sitter_ocaml.download]]
    sha256 = "e40250042b5937c15a1c0454dd963801daea1670185969d4c2db8cae8330ba99"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.aarch64-apple-darwin.tar.gz"
[[tree_sitter_ocaml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f79fe01fcb3133e964ef7204d431f20d5f9653b1"
libc = "glibc"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "b3be21224ade7b42ae4fb4e080babf7509ebcf25de8fedff9fb695bbd651653c"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.aarch64-linux-gnu-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd4b13bd9c6f7c34d60e342c762dffc2f6178819"
libc = "musl"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "4f9a38b987bb8935cec38cc2ca75fa81e2b6668bb6da5ea8133a77482b41cfbf"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.aarch64-linux-musl-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "aarch64"
git-tree-sha1 = "d5abadfc1ec7b205c6b7e005da8800ccef75e2ab"
os = "freebsd"

    [[tree_sitter_ocaml.download]]
    sha256 = "88480f988067331bdb09aa3a4bbed4f65baf4ca681e5d676d7ae2b8719faefe9"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.aarch64-unknown-freebsd.tar.gz"
[[tree_sitter_ocaml]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a04d128cb0ef5836e48ffa99c573978b5869dc4"
libc = "glibc"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "40e6efb9afc385ac2f439e36cb5867b2fa8b4d9d3728575673986fb442321e0e"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "065bb28ef551797be2a7d41bf6fc150fb38a927d"
libc = "musl"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "14c272e6e7e7a94690c0644f4cf615ebc87c023d76f456046ded21a2caef301b"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f94593529edb256aa63c0be6c5cddfbb55db489c"
libc = "glibc"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "9a1c4efbe66dec738c48fa497cbb2388e601085a36c4fefbb0d39500d66cac4a"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d2b29cd769d6d36e2be1ad1e5a3d6489a1c48b8"
libc = "musl"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "afeb9ad031d082de2dd450f97f4e59fcaf9d5a8b78b594a3f4224ace9b805708"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4a33556cfca1278bc6c244ab93f74f6542fa5fa"
libc = "glibc"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "caecac249fa8f84386d9c4c33ffb6f351b642a42c29e5000fa106d1b3e46566f"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.i686-linux-gnu-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33feece39299058ecd024c78390dc16ebe86a990"
libc = "musl"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "4af7e8e394fbdbea41bf254bcd67650ced7dcf6f56f9a8426638e60ae40d48bc"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.i686-linux-musl-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2f5df5989cf893e37e6d447896572aa5902fc89"
os = "windows"

    [[tree_sitter_ocaml.download]]
    sha256 = "548456a0295173b3f4f4280a93e0cedb359fcbf12f20def350d7b2c715ee62f0"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.i686-w64-mingw32-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3b6732b9bdaa67d5815acee2af1fdf094cb640a"
libc = "glibc"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "fc6a5d861332a4a8d6eb17da81d4a0efb7dec94cbf3095b6a49b737a6ae0d4ab"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24775bbbbbfaf7a8a871c59cb73b97135b94aec1"
libc = "glibc"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "999ebff8c4191a015b470fdc315c87ca509cd2fab7daf64c79c8cd6c0592f970"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.riscv64-linux-gnu-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "x86_64"
git-tree-sha1 = "65864637dea4fafc6238979d9e8e7aed79e6aafb"
os = "macos"

    [[tree_sitter_ocaml.download]]
    sha256 = "00e760c427ef4ed01c1986f73f396cbeef35eb4044d6a6b5ba0c3ccbb728b5da"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.x86_64-apple-darwin.tar.gz"
[[tree_sitter_ocaml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ea982c7d8666092380722c5e95ddf3cdaa20efe"
libc = "glibc"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "c283c979565a19f63d5c8c0577a7fce4afe7b4276e6b9fe64d48317f7abb3ba0"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.x86_64-linux-gnu-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e652c606772a7d8f58bb81e7767b17861511d7de"
libc = "musl"
os = "linux"

    [[tree_sitter_ocaml.download]]
    sha256 = "e069d1320e03296cdd4695faf36a6a2d4b758dd82c989649551b7bab4b6c1bef"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.x86_64-linux-musl-cxx11.tar.gz"
[[tree_sitter_ocaml]]
arch = "x86_64"
git-tree-sha1 = "398fcb4fa2cb0dc795f65c106d1e73b95984ea8e"
os = "freebsd"

    [[tree_sitter_ocaml.download]]
    sha256 = "64eb1e3db6f2b7ba52ade56fd91210f94ec5121e42ac8bf5798cc875fe63b83b"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.x86_64-unknown-freebsd.tar.gz"
[[tree_sitter_ocaml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4907a8187ea670d462be82617e72558746ef5c6a"
os = "windows"

    [[tree_sitter_ocaml.download]]
    sha256 = "bcd02cb54a9123243c58f7256c606f3dab22bbc0b12cc74e58a45ed2e74dfc76"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_ocaml_jll.jl/releases/download/tree_sitter_ocaml-v0.25.0+0/tree_sitter_ocaml.v0.25.0.x86_64-w64-mingw32-cxx11.tar.gz"
