# Autogenerated wrapper script for tree_sitter_ocaml_jll for i686-linux-musl-cxx11
export libtreesitter_ocaml, libtreesitter_ocaml_interface, libtreesitter_ocaml_type

JLLWrappers.@generate_wrapper_header("tree_sitter_ocaml")
JLLWrappers.@declare_library_product(libtreesitter_ocaml, "libtreesitter_ocaml.so")
JLLWrappers.@declare_library_product(libtreesitter_ocaml_interface, "libtreesitter_ocaml_interface.so")
JLLWrappers.@declare_library_product(libtreesitter_ocaml_type, "libtreesitter_ocaml_type.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_ocaml,
        "lib/libtreesitter_ocaml.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtreesitter_ocaml_interface,
        "lib/libtreesitter_ocaml_interface.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtreesitter_ocaml_type,
        "lib/libtreesitter_ocaml_type.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
