# Autogenerated wrapper script for tree_sitter_ocaml_jll for x86_64-apple-darwin
export libtreesitter_ocaml, libtreesitter_ocaml_interface, libtreesitter_ocaml_type

JLLWrappers.@generate_wrapper_header("tree_sitter_ocaml")
JLLWrappers.@declare_library_product(libtreesitter_ocaml, "@rpath/libtreesitter_ocaml.dylib")
JLLWrappers.@declare_library_product(libtreesitter_ocaml_interface, "@rpath/libtreesitter_ocaml_interface.dylib")
JLLWrappers.@declare_library_product(libtreesitter_ocaml_type, "@rpath/libtreesitter_ocaml_type.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_ocaml,
        "lib/libtreesitter_ocaml.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtreesitter_ocaml_interface,
        "lib/libtreesitter_ocaml_interface.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtreesitter_ocaml_type,
        "lib/libtreesitter_ocaml_type.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
