# Autogenerated wrapper script for tree_sitter_ocaml_jll for x86_64-w64-mingw32-cxx11
export libtreesitter_ocaml, libtreesitter_ocaml_interface, libtreesitter_ocaml_type

JLLWrappers.@generate_wrapper_header("tree_sitter_ocaml")
JLLWrappers.@declare_library_product(libtreesitter_ocaml, "libtreesitter_ocaml.dll")
JLLWrappers.@declare_library_product(libtreesitter_ocaml_interface, "libtreesitter_ocaml_interface.dll")
JLLWrappers.@declare_library_product(libtreesitter_ocaml_type, "libtreesitter_ocaml_type.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_ocaml,
        "bin\\libtreesitter_ocaml.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtreesitter_ocaml_interface,
        "bin\\libtreesitter_ocaml_interface.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtreesitter_ocaml_type,
        "bin\\libtreesitter_ocaml_type.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
